version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: ./backend/app
    container_name: go-app
    depends_on:
      - db
    environment:
      DB_URL: postgres://myuser:mypassword@db:5432/mydb?sslmode=disable
      PORT: 6060
    ports:
      - 6060:6060

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      VITE_PORT_BACKEND: http://127.0.0.1:6060
      VITE_ADDRESS_WALLET: UQCmVMcJSagWMqMBVruVbxSfha3ebbbcRFvSCOzMzvP_BDpW
    ports:
      - 8080:8080

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
