version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5432:5432

  app:
    build: ./app
    container_name: go-app
    depends_on:
      - db
    environment:
      DB_URL: postgres://myuser:mypassword@db:5432/mydb?sslmode=disable
      PORT: 8080
    networks:
      - app-network
    expose:
      - '8080'

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    ports:
      - '443:443'
    networks:
      - app-network
    depends_on:
      - app

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
