import { FC } from 'react';

export const Faq = () => (
  <div className='w-full h-max mt-4 bg-uiGrayGradient flex flex-col gap-3 rounded-32 px-5 py-4'>
    <h2 className='text-2xl font-climate'>Market Overview</h2>

    {MapData.map((item) => (
      <Accordion key={item.id} heading={item.heading} description={item.description} />
    ))}
  </div>
);

type AccordionProps = {
  heading: string;
  description: string;
};

const Accordion: FC<AccordionProps> = ({ description, heading }) => (
  <div className='collapse collapse-arrow bg-uiLowGray'>
    <input type='radio' name='my-accordion-2' defaultChecked />
    <div className='collapse-title text-xl font-medium'>{heading}</div>
    <div className='collapse-content'>
      <p>{description}</p>
    </div>
  </div>
);

const MapData: Record<string, string>[] = [
  {
    id: '1',
    heading: 'What is Earn Ton?',
    description:
      'Earn Ton is a DeFi protocol that works on the TON blockchain. It helps users to manage their digital assets safely and earn profits.',
  },

  {
    id: '2',
    heading: 'How does Earn Ton generate profits?',
    description:
      'The protocol makes money by lending funds to other DeFi protocols, such as Evaa, DeDust, and Tonstakers. Earn Ton connects users with trusted financial protocols, making it a safe and transparent way to earn.',
  },

  {
    id: '3',
    heading: 'Which tokens can I use for staking?',
    description: 'Currently, you can stake only TON',
  },

  {
    id: '4',
    heading: 'How is the yield rate calculated?',
    description: 'The yield rate depends on the demand and the amount of liquidity in protocols like Evaa, DeDust, and Ton Stakers.',
  },

  {
    id: '5',
    heading: 'What are Earn Ton’s fees?',
    description:
      'Earn Ton takes a 1% fee. This fee is not charged directly from users. Instead, it is taken from the yield generated by other protocols, so it does not reduce your earnings',
  },

  {
    id: '6',
    heading: 'What is the minimum amount I can stake?',
    description: 'The minimum amount you need to stake is 1 TON',
  },

  {
    id: '7',
    heading: 'How are rewards paid out?',
    description: 'Rewards are automatically sent to the same wallet from which you made the deposit.',
  },
];
